export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const IS_LOADING = 'IS_LOADING';
export const GET_ERROR = 'GET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const RETRIEVE_PASSWORD = 'RETRIEVE_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const SET_FINDPASSWORD_USER = 'SET_FINDPASSWORD_USER';
export const GET_BACKEND_DATA = 'GET_BACKEND_DATA';

export const ADD_PRODUCT_FAVORITE_LIST = 'ADD_PRODUCT_FAVORITE_LIST';
export const REMOVE_PRODUCT_FAVORITE_LIST = 'REMOVE_PRODUCT_FAVORITE_LIST';
export const EMPTY_PRODUCT_FAVORITE_LIST = 'EMPTY_PRODUCT_FAVORITE_LIST'

export const GET_PRODUCT_FAVORITE_LIST = 'GET_PRODUCT_FAVORITE_LIST';