export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';


export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const IS_LOADING = 'IS_LOADING';
export const GET_ERROR = 'GET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const RETRIEVE_PASSWORD = 'RETRIEVE_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const SET_FINDPASSWORD_USER = 'SET_FINDPASSWORD_USER';
export const GET_BACKEND_DATA = 'GET_BACKEND_DATA';

export const ADD_PRODUCT_FAVORITE_LIST = 'ADD_PRODUCT_FAVORITE_LIST';
export const REMOVE_PRODUCT_FAVORITE_LIST = 'REMOVE_PRODUCT_FAVORITE_LIST';
export const EMPTY_PRODUCT_FAVORITE_LIST = 'EMPTY_PRODUCT_FAVORITE_LIST'

export const GET_PRODUCT_FAVORITE_LIST = 'GET_PRODUCT_FAVORITE_LIST';


export const ADD_PRODUCT_SHOPPING_CART = 'ADD_PRODUCT_SHOPPING_CART';
export const REMOVE_PRODUCT_SHOPPING_CART = 'REMOVE_PRODUCT_SHOPPING_CART';
export const GET_PRODUCT_SHOPPING_CART = 'GET_PRODUCT_SHOPPING_CART';
export const EMPTY_PRODUCT_SHOPPING_CART = 'EMPTY_PRODUCT_SHOPPING_CART';

export const SAVE_SHIPPING_INFORMATION = 'SAVE_SHIPPING_INFORMATION';
export const SAVE_PAYMENT = 'SAVE_PAYMENT';
export const ON_SUCCESS_BUY = 'ON_SUCCESS_BUY';