export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const IS_LOADING = 'IS_LOADING';
export const GET_ERROR = 'GET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const RETRIEVE_PASSWORD = 'RETRIEVE_PASSWORD';